apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
    spec:
      containers:
        - name: otelcol
          image: {{ .Values.otelcol.image }}
          args: ["--config=/etc/otelcol/config.yaml"]
          ports:
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 8888
            - containerPort: 8889
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: otelcol-config
