apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.ports.amqp }}
      targetPort: 5672
    - name: management
      port: {{ .Values.rabbitmq.ports.management }}
      targetPort: 15672
  type: LoadBalancer
