apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | quote }}
